/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.Scanner;

public class Library {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
    }
    
    public static void main(String [] args) throws FileNotFoundException {
    	System.out.println("runs");
    	Scanner input = new Scanner(new FileReader(new File("Noun.txt").getAbsolutePath()));
    }
}
